### ISSUE TITLE
class "Validator" from namespace "HeimrichHannot\Haste\Util"

### ISSUE THREAD

**Issue by operatorone** [heimrichhannot/contao-advanced-member-bundle#3]
**Context**
Contao version: 4.9.34
Bundle version: 0.1.4
PHP version: 7.4

**Description**
If I activate the additional field in the config.yml 

huh_advanced_member:
  enable_additional_title_fields: true
  enable_additional_job_fields: true
  enable_image_fields: true
  enable_social_fields: true

do a DB update and try to add an URL i.e. in the field "LinkedIn-Profil" I get the following error displayed:

`Attempted to load class "Validator" from namespace "HeimrichHannot\Haste\Util". Did you forget a "use" statement for e.g. "webignition\RobotsTxt\Directive\Validator", "Netzmacht\Contao\Toolkit\Data\Alias\Validator", "Lcobucci\JWT\Validator" or "Lcobucci\JWT\Validation\Validator"?`

**Comment by koertho** [comment]
Fixed in 0.1.5, thanks for reporting!
